name: Lint

on: push

jobs:
  lint:
    strategy:
      matrix:
        go-version: [1.20.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    	name: cimon sec
          uses: cycodelabs/cimon-action@v0
          with:
            report-process-tree: true
            apply-fs-events: true
      - uses: actions/checkout@v4
      - name: lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=3m -v
